"""Add User table

Revision ID: 2450c90e4636
Revises: ff88679e45bb
Create Date: 2022-09-20 18:38:55.637029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2450c90e4636'
down_revision = 'ff88679e45bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_start_timestamp', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('is_stopped', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_first_start_timestamp'), 'user', ['first_start_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_first_start_timestamp'), table_name='user')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'is_stopped')
    op.drop_column('user', 'first_start_timestamp')
    # ### end Alembic commands ###
