"""Update User table

Revision ID: 2ed67a5f414d
Revises: cb50363a3d09
Create Date: 2022-09-21 03:13:11.953772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ed67a5f414d'
down_revision = 'cb50363a3d09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_start_timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_stopped', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_user_first_start_timestamp'), 'telegram_user', ['first_start_timestamp'], unique=False)
    op.drop_index('ix_TelegramUser_first_start_timestamp', table_name='TelegramUser')
    op.drop_table('TelegramUser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TelegramUser',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"TelegramUser_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('first_start_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_stopped', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='TelegramUser_pkey')
    )
    op.create_index('ix_TelegramUser_first_start_timestamp', 'TelegramUser', ['first_start_timestamp'], unique=False)
    op.drop_index(op.f('ix_telegram_user_first_start_timestamp'), table_name='telegram_user')
    op.drop_table('telegram_user')
    # ### end Alembic commands ###
