"""User: add account_address

Revision ID: 326b41e647d6
Revises: 2ed67a5f414d
Create Date: 2022-09-22 01:41:31.441614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326b41e647d6'
down_revision = '2ed67a5f414d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_user', sa.Column('account_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_user', 'account_address')
    # ### end Alembic commands ###
