"""User: add balance

Revision ID: 96bb2df667b0
Revises: 326b41e647d6
Create Date: 2022-09-22 05:16:52.081304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96bb2df667b0'
down_revision = '326b41e647d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_user', sa.Column('balance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_user', 'balance')
    # ### end Alembic commands ###
